### PR TITLE
Add unit tests for handle_and_remove function

### LINKED ISSUE #17: Write Unit Tests for `handle_and_remove` Function
- **Description**: Write unit tests to validate the behavior of the `handle_and_remove` function. Test cases should cover:
     - Successfully deleting a file.
     - Handling a `FileNotFoundError`.
     - Handling a `PermissionError`.
     - Handling other exceptions.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/utils.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

### PR DESCRIPTION
**Pull request by Varun-malviya5**
Fixes #17 
This pull request adds unit tests for the `handle_and_remove` function located in `utils.py`. 
I have also checked that all the test cases are passes or not
Screenshot 2024-10-03 010026

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@Varun-malviya5 
everything looks good 
but remove the empty `python` file you added 
and try to follow PR template 
add which issue gets fixed after this PR gets merged

**Comment by Kota-Karthik** [comment]
@Varun-malviya5 
You should add issue number in PR description 
not PR number
just update it 
other than that everything looks good

**Comment by Varun-malviya5** [comment]
now have a look pls
i am trying to delete that empty file but my command prompt is showing error please have a look to this

**Comment by Kota-Karthik** [comment]
LGTM!
@Varun-malviya5

**Pull request merged**
