### PR TITLE
Update README.md

### LINKED ISSUE #65: [Documentation Request: Add Index Page]
#### **What documentation needs to be updated?**
The project's documentation needs an index page to provide users with a clear overview of the structure and contents.

#### **Describe the changes needed**
An index page should be added at the beginning of the documentation, listing key sections with links to corresponding parts of the document. Each section, such as "Introduction," "Installation," "Usage," "API Reference," and "Contributing," should be hyperlinked for easy navigation.

#### **Additional context**
The index page will improve the user experience by making it easier to navigate through the project documentation.

### PR DESCRIPTION
**Pull request by GUNJESH843**
To enhance the TwinTrim documentation, consider incorporating the following table of contents:

## Table of Contents

1. [Introduction](#introduction)
2. [Features](#features)
3. [Installation](#installation)
4. [Usage](#usage)
   - [Basic Usage](#basic-usage)
   - [Advanced Options](#advanced-options)
5. [Contributing](#contributing)
6. [License](#license)

Here’s the formatted template to use for your GitHub pull request:

---

## Description

Added a table of contents to the documentation to improve navigation. This change enhances the usability of the documentation by allowing users to quickly locate sections.

- Fixes #65

## Type of change

Please delete options that are not relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@GUNJESH843 
I think we already have a `README.MD` , but its an really good idea to add a Index page 
but could you just add index page within the `README.MD`

**Comment by GUNJESH843** [comment]
@Kota-Karthik This PR is for the same I have edited and added a table of contents within the readme.md file itself

Please look into it and I have not received any Gssoc badge I am Gssoc contributor 

Regards,
@GUNJESH843

**Comment by Kota-Karthik** [comment]
@GUNJESH843 
We already have a `CONTRIBUTION.MD` file , it has a typo a `CONSTRIBUTION.MD`
please hyperlink it in the Contributing section and also fix the typo of `CONSTRIBUTION.MD` to  `CONTRIBUTION.MD`

**Comment by Kota-Karthik** [comment]
@GUNJESH843 
Are you working on it?

**Comment by GUNJESH843** [comment]
yes I have worked on it and created a pr #79  review it once

**Comment by GUNJESH843** [comment]
@Kota-Karthik @techy4shri, I believe there’s been some misunderstanding. Before jumping to conclusions, it would be helpful to consider the context.

@Kota-Karthik specifically asked me to fix the typo (as referenced here: https://github.com/Kota-Karthik/twinTrim/pull/66#issuecomment-2393919495). I made the necessary changes as requested, but now the PR has been closed, and I'm being told that file name changes are not allowed.

Could you please clarify why I was asked to make these changes if the file name adjustment wasn’t acceptable? 
Also, why was this PR closed without any comments explaining the decision?

Thanks for your time; I hope you respect mine as well.

**Comment by techy4shri** [comment]
You do not raise a PR specifically for file change, like you did in the other one. We cannot accept that as part of the program.
Also, readme contributions are highly discouraged, as you haad been assigned, I will wait for the review from @Kota-Karthik 
but I see you have deleted the branch.

**Comment by techy4shri** [comment]
You do not raise a PR specifically for file change, like you did in the other one. We cannot accept that as part of the program.
Also, readme contributions are highly discouraged, as you haad been assigned, I will wait for the review from @Kota-Karthik
but I see you have deleted the branch.

**Comment by techy4shri** [comment]
I checked with the PA and no, ther has been no misunderstanding and I can tell you with certaininty that I am not jumping to conclusions here. Yes, I can see that he asked you to fix the typo but rather than raisign a new PR, you could have simply made another commit in this one. So this PR will remian closed now.

**Pull request closed without merging**
