### PR TITLE
Test compare and replace

### LINKED ISSUE #3: Mock File Operations in `compare_and_replace` Tests
- **Description**: Mock file operations in the `compare_and_replace` tests to simulate different file system behaviors, such as:
     - Creating files with different modification times.
     - Mocking file deletion via `handle_and_remove`.
   - **Resources**: Refer to the [pytest mocking section](https://docs.pytest.org/en/stable/getting-started.html) for instructions on using `unittest.mock`.
   - **Path**: `twinTrim/dataStructures/allFileMetadata.py`
   - **Code to be added**: `tests`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests.

### PR DESCRIPTION
**Pull request by eleensmathew**
## Description
Wrote tests for replace_and_compare

- Fixes #3

## Type of change
- [x] Tests update

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@eleensmathew 
Everything is perfect 
can you just provide me the necessary screenshot to verify every test is working fine without any failures

**Comment by eleensmathew** [comment]
Hi i am also implementing the delete old messages feature as well. And also the websocket. Shall i complete that first or so you want to close the pr now?

**Comment by eleensmathew** [comment]
Ya sure

**Comment by eleensmathew** [comment]
image

**Comment by Kota-Karthik** [comment]
Can you just resolve the conflicts?
@eleensmathew

**Pull request closed without merging**
