### PR TITLE
Update Color Palette in CLI

### LINKED ISSUE #24: Replace Inconsistent Color Palette with an Optimal Color Palette for CLI Outputs
**Description:**  
The current color palette used in the CLI outputs is inconsistent, making it difficult for users to differentiate between various types of messages (e.g., informational, warning, success). An optimal color palette should be implemented to enhance the readability and user experience of the CLI. The new palette should provide clear visual distinctions for different message types and maintain accessibility standards.

**Resources:**  
- [Beaupy Documentation](https://beaupy.readthedocs.io/en/latest/) for color usage in CLI applications.  
- Best practices for color choices in user interfaces to ensure accessibility and usability.  
- Color contrast checker tools for ensuring optimal readability.

**Path:**  
`twinTrim/flags.py`

**Note:**  
Ensure to maintain the file structure as per the existing files and tests.

### PR DESCRIPTION
**Pull request by mienpham04**
## Description

Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.

- Fixes #24 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [✓] My code follows the style guidelines of this project
- [✓] I have performed a self-review of my own code
- [✓] I have commented my code, particularly in hard-to-understand areas
- [✓] My changes generate no new warnings
- [✓] New and existing unit tests pass locally with my changes
- [✓] I have maintained a clean commit history by using the necessary Git commands
- [✓] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Comment by Wahid7852** [comment]
Hey @mienpham04 Please create a single PR for addressing a single issue. You can do multiple commits for fixing your stuff but please close your PR #93 and merge it with this one.

**Comment by techy4shri** [comment]
@mienpham04 please follow the PR template and make single PR. Fix the conflicts in this and if you have any questions, do not hesitate to reach out to any of us on Discord!

**Comment by Kota-Karthik** [comment]
@mienpham04 
Your PR have merge conflicts 
Please fix them

**Comment by techy4shri** [comment]
Closing this as this looks like a duplicate of the other.

**Pull request closed without merging**
