### PR TITLE
Add Fuzzy Matching Feature to Enhance Duplicate Detection

### LINKED ISSUE #84: Add Fuzzy Matching Feature to Enhance Duplicate Detection
I would like to propose a new feature to enhance the duplicate detection capabilities of TwinTrim by introducing fuzzy matching technique. Currently, the tool relies on strict hashing to identify duplicate files, which works well for exact duplicates. However, many users might encounter near-duplicate files—files that are not identical but share high content similarity (e.g., different versions of documents, edited images).

The fuzzy matching feature would:

- Use similarity metrics (such as Jaccard index or Levenshtein distance) to detect files with slight differences.
- Help identify near-duplicates, reducing redundancy and improving storage efficiency.
- Allow users to set a similarity threshold to control the sensitivity of the fuzzy matching.

I have already implemented an initial version of this feature by creating a new _fuzzy.py_ file. This includes a method _find_fuzzy_duplicates_ that uses fuzzy matching to detect near-duplicates.

If you like the idea, please assign me  the task of developing upon this feature @Kota-Karthik

### PR DESCRIPTION
**Pull request by anushka4124**
## Description

Currently, the tool relies on strict hashing to identify duplicate files, which works well for exact duplicates. However, many users might encounter near-duplicate files—files that are not identical but share high content similarity (e.g., different versions of documents, edited images).

- Fixes #84 

## Implemented Fuzzy Duplicate Detection Method

The fuzzy matching feature would:

- Use similarity metrics (such as Jaccard index or Levenshtein distance) to detect files with slight differences.
- Help identify near-duplicates, reducing redundancy and improving storage efficiency.
- Allow users to set a similarity threshold to control the sensitivity of the fuzzy matching.

I have already implemented an initial version of this feature by creating a new fuzzy.py file. This includes a method find_fuzzy_duplicates that uses fuzzy matching to detect near-duplicates.

**Key Changes:**

- Introduced fuzzy matching logic to detect near-duplicate files based on content similarity.
- Added an optional --fuzzy flag to the CLI to enable this feature.
- Allows users to specify a similarity threshold for fine-tuned results.

**Why This Is Beneficial:**

- Expands the tool's use cases to handle not just exact duplicates but near-duplicates as well.
- Provides a more flexible, user-friendly duplicate management experience.
- Helps free up more storage space by eliminating similar files that might have been missed with strict hashing.

### CODE REVIEW

**Comment by techy4shri** [comment]
@anushka4124 screenshots please to verify that this runs properly.

**Comment by anushka4124** [comment]
> @anushka4124 screenshots please to verify that this runs properly.

Sure!

**Comment by anushka4124** [comment]
It's working fine!

Screenshot 2024-10-06 at 6 16 40 PM
Screenshot 2024-10-06 at 6 17 47 PM
Screenshot 2024-10-06 at 6 18 03 PM
Screenshot 2024-10-06 at 6 18 21 PM


So basically I had created 2 files in different subdirectories but both of them had the same file content under slightly different name. And thus, using the Fuzzy Duplicate Detection method, I was able to delete the duplicate which otherwise would have been overlooked by the previous duplicate file detection algorithm. I hope now you will merge my Pull request

**Comment by techy4shri** [comment]
@anushka4124 resolve the conflicts in this branch and wait for further review.

**Comment by techy4shri** [comment]
@anushka4124 can you check once more for any conflicts and share a screenshot whether the code is running properly? I will merge this as soon as you confirm from your side.

**Comment by techy4shri** [comment]
@anushka4124 you have 1 day to resolve conflicts or ask for help before I close this PR.

**Comment by Kota-Karthik** [comment]
@anushka4124 
Code looks fine 
I see that you also added flag to set threshold 
can you just update the `readme.MD` with the changes you made?
also just make sure these new updates aren't affecting any other initial functionality of the project

**Review by Kota-Karthik — CHANGES_REQUESTED** [review]
@anushka4124 
if you don't reply by the EOD.
I will be closing this PR.

**Comment by techy4shri** [comment]
This PR is being closed due to no response from the contributor and will not be opened again.

**Pull request closed without merging**
