### PR TITLE
Updates.py

### PR DESCRIPTION
**Pull request by Khushi-Dua**
## Description

Here’s a concise analysis of the code:

1. **Hardcoded Path for Non-Existent File**:
   - The test for a non-existent file uses a fixed path, which can lead to issues if the environment changes. Using a dynamic path (like `tmp_path`) ensures portability across platforms.

2. **Assertion Enhancements**:
   - The test for an existing file asserts `modification_time > 0`, assuming a positive timestamp indicates a valid file. However, adding an `isinstance` check ensures the return type matches expectations, enhancing robustness.

3. **Error Handling Expectations**:
   - The `test_get_modification_time_non_existing_file` expects `-1` for non-existent files. This assumption should be confirmed by the `AllFileMetadata` class to ensure consistent handling of errors without throwing exceptions.

4. **Improved Descriptions**:
   - Slightly refining docstrings would clarify the intent of each test, making the code easier to understand and maintain.

These adjustments will make the tests more reliable, readable, and adaptable to different environments.

- Fixes #154

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update
- [x] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@Khushi-Dua 
please strictly follow the PR template, only after that your PR will be reviewed!

**Comment by Wahid7852** [comment]
Waiting for a response @Khushi-Dua. If no response under 24 hours then this PR will be closed.

**Comment by Khushi-Dua** [comment]
> @Khushi-Dua please strictly follow the PR template, only after that your PR will be reviewed!

 @Kota-Karthik what is PR template?

**Comment by Kota-Karthik** [comment]
@Khushi-Dua 
A PR template is a MD file that have some structure and you follow it when you open a PR
You did use the PR template but didn't fill all information like issue number, screenshots, description etc.

**Comment by techy4shri** [comment]
@Khushi-Dua reply by tonight or I will be closing this PR. If you need more help, ask your doubts and questions on discord channel.

**Comment by Khushi-Dua** [comment]
Filled the PR template

**Comment by techy4shri** [comment]
@Khushi-Dua you need to resolve the conflicts in this PR.

**Comment by techy4shri** [comment]
@Kota-Karthik I see the branch used is main.....think we should ask her to rebase?

**Comment by Kota-Karthik** [comment]
> @Kota-Karthik I see the branch used is main.....think we should ask her to rebase?

@Khushi-Dua 
please check your branch , 
you should have made another branch before making any changes !
please fix it!

**Comment by Wahid7852** [comment]
all that is fine but... @Khushi-Dua what issue are you actually creating a PR for?

**Comment by techy4shri** [comment]
Closing this due to multiple issues. @Khushi-Dua raise a new PR and on a different branch. Never make any changes on the main branch.

**Pull request closed without merging**
