### PR TITLE
Added the test file for setMinFileSize

### LINKED ISSUE #12: Write Unit Tests for `setMinFileSize` Method
- **Description**: Write unit tests to validate the behavior of the `setMinFileSize` method. Ensure that it correctly sets the minimum file size and that it can handle invalid inputs.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for setting up tests.
   - **Path**: `twinTrim/dataStructures/fileFilter.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

### PR DESCRIPTION
**Pull request by harshitpathak528**
## Description

As mentioned I added the test file for setMinFileSize  

- Fixes #12 

## Type of change

Please delete options that are not relevant.

- [X] Tests update

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] I have maintained a clean commit history by using the necessary Git commands
- [X] I have checked that my code does not cause any merge conflicts

### CODE REVIEW

**Comment by techy4shri** [comment]
@harshitpathak528 you need to add screenshots for showing the output

**Comment by harshitpathak528** [comment]
Please check the code you will easily understand, also added comments for clarification .

**Comment by techy4shri** [comment]
Unless you add screenshot or any media related to the code as per the format of the PR, it will not be accepted. You have a day to comply or this PR will be rejected.

**Comment by techy4shri** [comment]
@harshitpathak528 you have 2 more day to comply and add the required screenshots and write a detailed description in the PR above for this to be merged properly otherwise I will be closing this.

**Comment by techy4shri** [comment]
This PR is being closed due to the contributor not complying with the requests made and will not be opened again.

**Pull request closed without merging**
