### PR TITLE
updated Dry Run feature

### LINKED ISSUE #58: [Feature] addition of dry run mode
I can Introduce a --dry-run option to simulate deletion, allowing users to see what would be removed without actually deleting anything.
this may enhance the project please assign me to add this.

### PR DESCRIPTION
**Pull request by adityakalburgi**
Hi @techy4shri, @Kota-Karthik 

Thank you for your feedback! I apologize for not following the PR template initially. I’m currently updating the PR with the required information.

## Description

Updated the README.md to clarify project setup instructions.
Added a dry run feature in flags.py, which will display the files that would be deleted without actually removing them. This allows users to review the potential deletions before making any changes.

- Fixes #58 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)
Screenshot 2024-10-17 194025

### CODE REVIEW

**Comment by techy4shri** [comment]
@adityakalburgi I would suggest you follow the PR guidelines. Fill the template I have given here. It is needed so as to facilitate point assignment and any future review. 
Also, please maintain a clean commit history by squashing all the commits. You can do so by follwowing the steps below:
1. `git fetch origin`
2.  `git rebase -i HEAD~5`
3. `squash <commit message>`
4. `git push --force`
Wait for review from Karthik afterwards.

**Review by techy4shri — CHANGES_REQUESTED** [review]
@adityakalburgi I would suggest you follow the PR guidelines. Fill the template I have given here. It is needed so as to facilitate point assignment and any future review.
Also, please maintain a clean commit history by squashing all the commits. You can do so by follwowing the steps below:
1. `git fetch origin`
2. `git rebase -i HEAD~5`
3. `squash <commit message>`
4. `git push --force`
Wait for review from Karthik afterwards.

**Review by Kota-Karthik — CHANGES_REQUESTED** [review]
@adityakalburgi 
please follow the PR template 
only then any changes would be reviewed

**Comment by Wahid7852** [comment]
Waiting for a response @adityakalburgi. Failure in responding within 24 hours will lead to me closing your PR.

**Comment by adityakalburgi** [comment]
> Waiting for a response @adityakalburgi. Failure in responding within 24 hours will lead to me closing your PR.

Hi i am soo updating the PR thank you..

**Comment by Kota-Karthik** [comment]
@adityakalburgi 
I noticed something about your PR 
I think you hadn't pulled changes before making changes 
Which will cause problems 
So i request you to pull the changes , then make a PR

**Comment by techy4shri** [comment]
@adityakalburgi update?

**Review by techy4shri — CHANGES_REQUESTED** [review]
Jull sync your fork and pull changes once to ensure you are up-to-date with everything and then we will be happy to merge your PR!

**Comment by adityakalburgi** [comment]
> Jull sync your fork and pull changes once to ensure you are up-to-date with everything and then we will be happy to merge your PR!

Ok sure will do it soon...

**Review by Kota-Karthik — CHANGES_REQUESTED** [review]
@adityakalburgi 
please make changes as requested!

**Comment by adityakalburgi** [comment]
> Jull sync your fork and pull changes once to ensure you are up-to-date with everything and then we will be happy to merge your PR!

hi @techy4shri i have sync my fork please have a look thank you!

**Comment by techy4shri** [comment]
@adityakalburgi will do soon. Wait for review from Karthik.

**Comment by Wahid7852** [comment]
@Kota-Karthik review ra pls

**Review by Kota-Karthik — CHANGES_REQUESTED** [review]
@adityakalburgi 
Your pr still removes most of the code 
like logging and other interactive cli code
please fix it!

**Comment by adityakalburgi** [comment]
hi @Kota-Karthik i have updated my PR!

**Comment by Wahid7852** [comment]
I will say to close this PR, delete your fork of TwinTrim, Then refork the repo, do your changes on the new fork and then submit a new PR

This PR now is looking dirty with so many redundant merges.

**Comment by techy4shri** [comment]
Squash the commits and make the commit history clean please or raise a new PR.

**Comment by Kota-Karthik** [comment]
@adityakalburgi 
If you fail to follow the instructions I gave you on discord 
I will be closing this PR by EOD tomorrow

**Comment by adityakalburgi** [comment]
> @adityakalburgi If you fail to follow the instructions I gave you on discord I will be closing this PR by EOD tomorrow

I will create a new PR so you can close this one

**Pull request closed without merging**
