### PR TITLE
Updated fileFilter.py

### PR DESCRIPTION
**Pull request by SandyK1002**
Added the unit tests to addFileExclude method in fileFilter.py using pytest

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@SandyK1002 
write these tests in a separate file within the tests folder 
whenever you make a PR  ,please mention the issue number and screenshots that show the tests run fine without any failures in the comment

**Comment by Kota-Karthik** [comment]
@SandyK1002 
are you working on it?

**Comment by techy4shri** [comment]
@SandyK1002 if you do not reply within a day, this PR will be closed and your contribution won't be counted.

**Comment by techy4shri** [comment]
This PR is being closed because of no response from the contributor's side.

**Pull request closed without merging**
