### PR TITLE
added test to add_or_update_file when file doesnt exist

### LINKED ISSUE #5: Write Tests for Handling Missing Files in `add_or_update_file`
- **Description**: Write tests for `add_or_update_file` that simulate cases where a file doesn't exist. The function should handle these cases gracefully, avoiding crashes or incorrect metadata.
   - **Resources**: Use the [pytest guide](https://docs.pytest.org/en/stable/getting-started.html) for setting up test cases with `FileNotFoundError` handling.
   - **Path**: `twinTrim/dataStructures/allFileMetadata.py`
   - **Code to be added**: `tests`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests.

### PR DESCRIPTION
**Pull request by eleensmathew**
Wrote test to check if file exists for the add_or_update_file function. Used pytest-mock for creating mocks and pytest. Fixes #5

### CODE REVIEW

**Comment by eleensmathew** [comment]
@techy4shri Can you review this PR

**Comment by Kota-Karthik** [comment]
@eleensmathew 
can you just add screenshots , so that we can verify , all tests run well without any failure?

**Comment by eleensmathew** [comment]
image

**Comment by Kota-Karthik** [comment]
@eleensmathew 
Can you just resolve the conflicts?

**Comment by techy4shri** [comment]
Make a new PR on a different branch with proper media to show the tests run and only change the file needed.

**Comment by eleensmathew** [comment]
I think its closed?

**Comment by techy4shri** [comment]
> I think its closed?

It is.

**Pull request closed without merging**
