### PR TITLE
Added unit tests for setMinFileSize method in fileFilter Class. Fixes #12

### LINKED ISSUE #12: Write Unit Tests for `setMinFileSize` Method
- **Description**: Write unit tests to validate the behavior of the `setMinFileSize` method. Ensure that it correctly sets the minimum file size and that it can handle invalid inputs.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for setting up tests.
   - **Path**: `twinTrim/dataStructures/fileFilter.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

### PR DESCRIPTION
**Pull request by kushwxha**
This pull request introduces unit tests for the setMinFileSize method in the FileFilter class. The tests are designed to validate the following scenarios:

Setting valid minimum file sizes (e.g., "20kb", "5kb", "1kb").
Handling an empty string as the minimum file size.
Accepting special characters or random strings as minimum file size.
Setting numeric strings without units.
These tests ensure that the method behaves as expected based on the current implementation, which directly assigns the input to the minFileSize attribute without validation.

image

### CODE REVIEW

**Comment by kushwxha** [comment]
hey @Kota-Karthik, can you please check it now ?

**Comment by Kota-Karthik** [comment]
@kushwxha you told me you had resolved conflicts?
we have conflicts

**Comment by Kota-Karthik** [comment]
@kushwxha 
even this have conflicts 
please resolve them !

**Comment by kushwxha** [comment]
hey @Kota-Karthik , 
i am getting issues in this pr.
so can i create a new pr for this issues and then make changes it?

**Comment by kushwxha** [comment]
hey @Kota-Karthik ,
someone has changed the file names thats why i am getting conflict.
image

**Comment by kushwxha** [comment]
hey @Kota-Karthik ,
can you check it now?

**Comment by Kota-Karthik** [comment]
@kushwxha 
Can you just squash necessary commits for  a clean commit history ?
Make it in a single commit!

**Comment by kushwxha** [comment]
Ok

**Comment by kushwxha** [comment]
hey @Kota-Karthik ,
 can you check it now??

**Comment by kushwxha** [comment]
hey @Kota-Karthik,
can you check this pr and give review??

**Comment by kushwxha** [comment]
Ok

**Comment by techy4shri** [comment]
@kushwxha kindly make the necessary changes or I will be closing this PR and you can raise a new one with a clea commit history.

**Comment by kushwxha** [comment]
Ok

**Comment by kushwxha** [comment]
hey @techy4shri,
can you please help me that how can i squash the necessary commits in one and drop other commits?
if you will help me, i will complete this pr by tomorrow morning.

**Comment by techy4shri** [comment]
@kushwxha you have been unassigned from the issue. This PR will be closed now.

**Pull request closed without merging**
