### PR TITLE
added the dry Run feature

### LINKED ISSUE #58: [Feature] addition of dry run mode
I can Introduce a --dry-run option to simulate deletion, allowing users to see what would be removed without actually deleting anything.
this may enhance the project please assign me to add this.

### PR DESCRIPTION
**Pull request by adityakalburgi**
## Description

Updated the README.md to clarify project setup instructions.
Added a dry run feature in flags.py, which will display the files that would be deleted without actually removing them. This allows users to review the potential deletions before making any changes.

- Fixes #58 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)
image

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Comment by adityakalburgi** [comment]
@Kota-Karthik please have a look on this PR thank you!

**Comment by techy4shri** [comment]
@adityakalburgi nice, clean and concise, just wait a bit and Karthik will review it!

**Review by techy4shri — CHANGES_REQUESTED** [review]
@adityakalburgi do not make any changes on main branch directly, that will create issues. 
Rebase your changes to another branch first. Afterwards, Karthik will review.

**Comment by techy4shri** [comment]
@adityakalburgi make the changes ASAP so I can merge this PR. You have one day to comply.

**Comment by adityakalburgi** [comment]
> @adityakalburgi make the changes ASAP so I can merge this PR. You have one day to comply.

Ok will do it soon

**Comment by Wahid7852** [comment]
@adityakalburgi any updates?

**Comment by adityakalburgi** [comment]
> @adityakalburgi any updates?

Soon updating

**Comment by adityakalburgi** [comment]
Hi @techy4shri i have created a new PR with new branch you can close this one thank you!

**Pull request closed without merging**
