### PR TITLE
added test_fileMetadata.py 

### LINKED ISSUE #7: Write Unit Tests for `insert_file` Method
- **Description**: Write unit tests to validate the `insert_file` method in the `FileMetadata` class. Test cases should include:
     - Inserting a new file into the metadata list.
     - Trying to insert a file that is already present.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for setting up tests.
   - **Path**: `twinTrim/dataStructures/fileMetadata.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

### PR DESCRIPTION
**Pull request by Sai-ganesh-0004**
**Description**
This PR introduces the file test_fileMetadata.py, which contains unit tests for the insert_file method in the FileMetadata class. These tests ensure that:

- A new file path can be successfully inserted into the metadata.
- Duplicate file paths are not added to the list

Fixes #7: Added unit tests for the insert_file method in the FileMetadata class to ensure that new files can be added correctly and that duplicates are not inserted.

**Type of change**

- [x]  Tests update

**Checklist**

- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x]  I have commented my code, particularly in hard-to-understand areas
- [x]  My changes generate no new warnings
- [x]  New and existing unit tests pass locally with my changes
- [x]  I have maintained a clean commit history by using the necessary Git commands
- [x]  I have checked that my code does not cause any merge conflicts

So what I have done is I have created 4 dummy files to test the behavior of the  `insert_file` method and tested based on that.

Screenshot 2024-10-09 085959

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@Sai-ganesh-0004 
delete this file `twinTrim/dataStructures/test_fileMetadata.py`

**Comment by Sai-ganesh-0004** [comment]
Can you check it once

**Comment by techy4shri** [comment]
@Sai-ganesh-0004 We will check this as soon as we can!

**Comment by Kota-Karthik** [comment]
@Sai-ganesh-0004 LGTM!

**Pull request merged**
