### PR TITLE
Optimize get_file_hash Function and Improve Large File Handling Fixes #20 

### LINKED ISSUE #20: Optimize `get_file_hash` Function for Large Files
- **Description**: Investigate the `get_file_hash` function to optimize it for very large files by possibly increasing the buffer size or using a more efficient hashing algorithm if necessary.
   - **Resources**: Refer to the [Python hashlib documentation](https://docs.python.org/3/library/hashlib.html) for more information on hashing algorithms.
   - **Path**: `twinTrim/utils.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

### PR DESCRIPTION
**Pull request by ShirshenduR**
## Description

This PR optimizes the `get_file_hash` function in `utils.py` to handle large files more efficiently. It increases the buffer size.

- Fixes #20
## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented where necessary
- [x] No new warnings
- [x] All unit tests pass
- [x] Clean commit history
- [x] No merge conflicts

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@ShirshenduR 
workflow is failing 
make necessary changes to fix it!

**Comment by ShirshenduR** [comment]
> @ShirshenduR workflow is failing make necessary changes to fix it!

I have changed the algorithm to blake2b it's testing for md5

**Comment by Kota-Karthik** [comment]
@ShirshenduR 
make necessary changes wherever necessary to fix the workflow

**Comment by techy4shri** [comment]
Only 1 issue per PR! Do not raise a PR for multiple issues please!

**Comment by ShirshenduR** [comment]
@Kota-Karthik please check now

**Comment by Kota-Karthik** [comment]
@ShirshenduR LGTM!

**Pull request merged**
