### PR TITLE
Fixes #24

### LINKED ISSUE #24: Replace Inconsistent Color Palette with an Optimal Color Palette for CLI Outputs
**Description:**  
The current color palette used in the CLI outputs is inconsistent, making it difficult for users to differentiate between various types of messages (e.g., informational, warning, success). An optimal color palette should be implemented to enhance the readability and user experience of the CLI. The new palette should provide clear visual distinctions for different message types and maintain accessibility standards.

**Resources:**  
- [Beaupy Documentation](https://beaupy.readthedocs.io/en/latest/) for color usage in CLI applications.  
- Best practices for color choices in user interfaces to ensure accessibility and usability.  
- Color contrast checker tools for ensuring optimal readability.

**Path:**  
`twinTrim/flags.py`

**Note:**  
Ensure to maintain the file structure as per the existing files and tests.

### PR DESCRIPTION
**Pull request by RhiyaBhat**
## Description

he current color palette used in the CLI outputs is inconsistent, making it difficult for users to differentiate between various types of messages (e.g., informational, warning, success).  The new palette should provide clear visual distinctions for different message types and maintain accessibility standards.

- Fixes #24 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [ ] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@RhiyaBhat 
can you just add screenshots to show us how the new color palette look for different situations?

**Comment by Wahid7852** [comment]
Waiting for your response @RhiyaBhat

**Comment by Wahid7852** [comment]
if no response in 24 hours @RhiyaBhat. i will be closing it

**Comment by RhiyaBhat** [comment]
> @RhiyaBhat can you just add screenshots to show us how the new color palette look for different situations?

Is it not working in other devices?

**Comment by techy4shri** [comment]
@RhiyaBhat it is contribution rule to add media and follow PR template while raising one. You have 24 hours to comply or I will be closing this PR. If you have a question or doubt, ask them on discord for more details or here.

**Comment by RhiyaBhat** [comment]
image

INFO_COLOR = 'blue'
WARNING_COLOR = 'yellow'
SUCCESS_COLOR = 'green'
ERROR_COLOR = 'red'

**Review by Kota-Karthik — APPROVED** [review]
@RhiyaBhat 
LGTM!

**Pull request merged**
