### PR TITLE
Added tests for find_duplicates

### LINKED ISSUE #22: Write Unit Tests for `find_duplicates` Function
- **Description**: Write unit tests for the `find_duplicates` function to ensure it behaves as expected. Test cases should cover:
     - Finding duplicates in a directory with multiple files.
     - Handling of directories with no files.
     - Proper filtering of files using `file_filter`.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/flagController.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

### PR DESCRIPTION
**Pull request by Sai-ganesh-0004**
## Description

This update introduces unit tests for the `find_duplicates` function in the `twinTrim.flagController` module. The tests cover various scenarios, including finding duplicate files, handling directories with no files, and proper filtering of files. These tests ensure the robustness of the duplicate detection functionality by validating its behavior in different contexts.

- Fixes #22 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

image

### CODE REVIEW

**Comment by Sai-ganesh-0004** [comment]
Want me to add anything else I will add

**Comment by Kota-Karthik** [comment]
@Sai-ganesh-0004 
I see no problems with the code , but let @techy4shri submit her review
will merge it ,if she doesn't request any changes!

**Comment by Sai-ganesh-0004** [comment]
@techy4shri Please review

**Review by techy4shri — APPROVED** [review]
Everything is working fantastic, I approve @Kota-Karthik !
@Sai-ganesh-0004 good work.

**Comment by Sai-ganesh-0004** [comment]
can you add gssoc-ext label for this pr

**Pull request merged**
