### PR TITLE
Created the compare_and_replace function tests

### LINKED ISSUE #2: Write Unit Tests for `compare_and_replace` Method
- **Description**: Write tests for the `compare_and_replace` method to ensure:
     - The correct file is removed based on the modification time.
     - No file is removed if one or both files don't exist.
   - **Resources**: Refer to the [pytest guide](https://docs.pytest.org/en/stable/getting-started.html) for test setup.
   - **Path**: `twinTrim/dataStructures/allFileMetadata.py`
   - **Code to be added**: `tests`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
## Description

Created the compare_and_replace function tests

- Fixes #2 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [X] Tests update

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] I have maintained a clean commit history by using the necessary Git commands
- [X] I have checked that my code does not cause any merge conflicts

@Kota-Karthik @techy4shri Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.

Please note 1 test was not successful it is deleting the file :- 

FAILED tests/allFileMetadata_compare_and_replace.py::TestAllFileMetadata::test_compare_and_replace_correct_file_removed - AssertionError: assert False

### CODE REVIEW

**Review by Kota-Karthik — CHANGES_REQUESTED** [review]
@tarunkumar2005 
can you fix workflows?
also please fix tests, and please add screenshots

**Comment by tarunkumar2005** [comment]
@Kota-Karthik @techy4shri Done the changes and here is the screenshot :- 

image

Please review it now.

**Review by tarunkumar2005 — COMMENTED** [review]
Done changes

**Comment by Kota-Karthik** [comment]
@tarunkumar2005 
LGTM!

**Review by Kota-Karthik — APPROVED** [review]

**Pull request merged**
