### PR TITLE
Update flags.py

### PR DESCRIPTION
**Pull request by vid0326**
## Description

-> Moved utility functions (print_info, print_success, print_warning, print_error, handle_and_remove, parse_size, get_file_hash) from main.py to utils.py to keep the code modular and reusable.

->Updated imports in main.py to reflect the new structure.

->Tested the new structure and confirmed that the code works as expected.

->Fixed the issue regarding the missing reference to print_success in utils.py.

->Ensured that the code generates no new warnings and that unit tests (if any) pass successfully.

This PR addresses Issue #59, which relates to improving code organization by moving reusable utility functions into a separate module (utils.py).

- Fixes #59

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [x] Tests update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)
image

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@vid0326 
its great 
everything looks good 
but can you just move these functions to `utils.py` and add screenshots to ensure the code works fine even after the changes

**Comment by vid0326** [comment]
Screenshot 2024-10-03 235228

**Comment by techy4shri** [comment]
@vid0326  Please fill the PR format properly to be given points properly. Add screenshot in the area provided andcheck the necessary boxes. Also mention the issue number so I can label this.

**Comment by vid0326** [comment]
issue number  #59 
Screenshot 2024-10-03 235228
updated flag.y utilis.py

**Comment by Kota-Karthik** [comment]
@vid0326 
you didn't make any changes as per my review
please make necessary changes then the PR will be good to merge!

**Comment by techy4shri** [comment]
@vid0326 what we need in this PR is this:

1. Move the updates you meade in the flags.py to utils.py
2. Remove any changes made in the flags.py
3. Commit those changes.
4. Push the changes.
5. Fill the PR template properly and tag us both.
6. Please include screenshots and comment on your code properly to ensure we can review it easily.
I hope I made things clear, if not feel free to ask on discord!

**Pull request closed without merging**
