### PR TITLE
Improve User Experience by Implementing Multi-Select #88

### LINKED ISSUE #88: Improve User Experience by Implementing Multi-Select
Currently , when duplicate files are found  in CLI, users can only select files using "space" key , which will only work for the first line and to select  other files we have to  use "a" key .This limitation make it difficult to select files as user need .

To enhance the user experience, i will be  implementing a more flexible selection feature that allows users to select any file at any time.

Benefits:
-Increased Flexibility: Users can quickly select multiple files as user intend to.
-Efficiency: This change would streamline the workflow, enabling users to manage their duplicate files more effectively.
-User-Friendly Interface: A more intuitive selection method would improve overall user satisfaction with the tool.

### PR DESCRIPTION
**Pull request by fluid111**
## Description
Currently it becomes confusing to navigate files for selection. Now users can use arrow keys to  navigate files to select , they can see the size of files on CLI and added an extra prompt ensuring they selected the files they intended to delete. So that they will not accidentally delete the files they did not intended  to .

## Type of change
- [x] New feature (non-breaking change which adds functionality)

Closes #88 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

Before
Screenshot 2024-10-11 082218
Screenshot 2024-10-11 082235

After
Screenshot 2024-10-11 082430

### CODE REVIEW

**Comment by fluid111** [comment]
can you add label for hacktoberfest and gssoc before merging

**Comment by Wahid7852** [comment]
Can you share images of how will this be working?

**Comment by fluid111** [comment]
Screenshot 2024-10-10 160116

**Review by techy4shri — CHANGES_REQUESTED** [review]
First and foremost, fill the PR description and all fields properly. Only then this PR will be reviewed. Those fields are for a purpose.

**Comment by fluid111** [comment]
> First and foremost, fill the PR description and all fields properly. Only then this PR will be reviewed. Those fields are for a purpose.

Can you check it if it is alright ?

**Comment by fluid111** [comment]
> First and foremost, fill the PR description and all fields properly. Only then this PR will be reviewed. Those fields are for a purpose.

is there anything that i can improve, please let me knoe

**Comment by techy4shri** [comment]
> > First and foremost, fill the PR description and all fields properly. Only then this PR will be reviewed. Those fields are for a purpose.
> 
> is there anything that i can improve, please let me know

Not right now, let the PA review this and I will let you know if anything else is needed!

**Review by Kota-Karthik — APPROVED** [review]
everything LGTM!
even code is clean

**Pull request merged**
