### PR TITLE
Added the logging feature

### PR DESCRIPTION
**Pull request by Kritika75**
Changes made to the file:

1. Basic Logging Configuration
2. Log for Deleting All Files Automatically
3. Log When Starting Duplicate Search
4. Error Logging During Duplicate Search
5. Log When No Duplicates Are Found
6. Log the Number of Duplicate Files Found
7. Log Details for Each Original File and Its Duplicates
8. Log Deleting Each Duplicate File
9. Error Logging During File Deletion
10.Log the Total Time Taken for the Operation

Issue resolved feature request logging #69

### CODE REVIEW

**Comment by Kritika75** [comment]
Hey, I've been trying to attach a screenshot all morning, but every time I add a file, it shows an error. Should I just copy and paste the terminal output to show you? @Kota-Karthik

**Comment by Kota-Karthik** [comment]
@techy4shri 
Can you review and merge this?

**Comment by techy4shri** [comment]
Sure.

**Comment by Kritika75** [comment]
It's worked:

log
twintrim02
twintrim
@techy4shri @Kota-Karthik

**Comment by Kota-Karthik** [comment]
@Kritika75 LGTM!

**Pull request merged**
