### PR TITLE
Optimize get_file_hash function and add tests for file sizes and algorithms. Fixes #20

### LINKED ISSUE #20: Optimize `get_file_hash` Function for Large Files
- **Description**: Investigate the `get_file_hash` function to optimize it for very large files by possibly increasing the buffer size or using a more efficient hashing algorithm if necessary.
   - **Resources**: Refer to the [Python hashlib documentation](https://docs.python.org/3/library/hashlib.html) for more information on hashing algorithms.
   - **Path**: `twinTrim/utils.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

### PR DESCRIPTION
**Pull request by ShirshenduR**
optimised get_file_hash by increasing the increasing buffer size to 128kb and also using blake2b algorithm and created test_utils.py to test it

### CODE REVIEW

**Comment by ShirshenduR** [comment]
#20 I have solved this

**Comment by Kota-Karthik** [comment]
@ShirshenduR , update the code according to the review. When creating a PR, mention 'Fixes `#<issue number>`' and include screenshots so I can verify. Also, please squash all the small commits into a single commit.

**Comment by Kota-Karthik** [comment]
@ShirshenduR 
Its great that you wrote tests but its an another issue #18 and its already assigned to someone else 
So i suggest you to remove that tests code completely

**Comment by ShirshenduR** [comment]
ok sir

**Comment by ShirshenduR** [comment]
sir is it now correct actually I am new to open source and git

**Comment by Kota-Karthik** [comment]
@ShirshenduR no problem 
Can you update algorithm at line number 21 , rather than in line number 19 
And try to squash all the commits into one 
Resources :- 
[git squash](https://www.git-tower.com/learn/git/faq/git-squash#:~:text=To%20%22squash%22%20in%20Git%20means,often%20done%20when%20merging%20branches. )

**Comment by ShirshenduR** [comment]
I have done according to what you said

> @ShirshenduR no problem Can you update algorithm at line number 21 , rather than in line number 19 And try to squash all the commits into one Resources :- [git squash](https://www.git-tower.com/learn/git/faq/git-squash#:~:text=To%20%22squash%22%20in%20Git%20means,often%20done%20when%20merging%20branches.)

**Comment by techy4shri** [comment]
There are multiple conflicts in your pull request.
You're to make changes only in the utils.py file. No other changes.
 Kindly either resolve the conflicts here or follow these steps to male a new pull request in a new branch:

1. Sync your forked repository on github.
2. `git pull origin main`
3. `git checkout -b <new branch name>` 
4.Make the changes as suggested in the review. Please do not make any changes in Readme.md file. Only edit the utils.py file.
5. `git add .`
6. `git commit -m "commit mesaage"`
7. `git push origin <new branch name>`
8. Come to this repo, head over to pull request.
9. Compare and make a new pill request.

**Pull request closed without merging**
