### PR TITLE
Update README.md by adding Table of Contents

### PR DESCRIPTION
**Pull request by Maryam0330**
## Description

This change updates the README.md file to now include a hyperlink based navigation which makes easier to access different sections of the long README file

- It doesn't exactly fix an existing issue but it will help make the documentation better 

## Type of change

Please delete options that are not relevant.

- [x] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

Add screenshots to help explain the changes (if necessary).

### CODE REVIEW

**Comment by Kota-Karthik** [comment]
@Maryam0330 
Please follow the PR template we provided
add issue number

**Comment by Maryam0330** [comment]
Done! 👍

**Comment by Maryam0330** [comment]
It doesn't solve a pre-existing issue, it's just a simple documentation update for better navigation. Do you want me to raise an issue first?

**Comment by techy4shri** [comment]
@Maryam0330 you need to go through the follwoing texts before making any PR:

1. Readme.md (super helpful in knowing the basics)
2. Contributing.md (THAT'S IMPORTANT DO NOT SKIP)

You do not raise a PR without raising an issue first and this repository does not accept readme contributions. Your PR is being rejected due to being invalid.

**Pull request closed without merging**
